// ═══════════════════════════════════════════════════════════════════════════════
// x402 Research — deep web-research as a paid x402 endpoint.
//
//   GET /api/x402/research?q=<question>&limit=5
//
// Runs Puls' production research pipeline (keyless Jina Reader + DuckDuckGo,
// with Exa/Tavily/Serper/Firecrawl fallbacks) over any question and returns a
// sourced brief + source list, ready to drop into an LLM prompt. Payable by
// ANY wallet via Circle Gateway x402 on Arc Testnet — the same rail our own
// swarm uses when it buys market data.
//
//   curl  https://api.pulsmarket.tech/api/x402/research?q=…        → 402 + terms
//   circle services pay "https://api.pulsmarket.tech/api/x402/research?q=…" \
//     --address <agentWallet> --chain ARC-TESTNET
// ═══════════════════════════════════════════════════════════════════════════════
import { x402Paywall } from './x402.js';
import { researchQuestion } from './agent_research.js';

const RESEARCH_PRICE = process.env.X402_RESEARCH_PRICE || '$0.01';

export function registerX402Research(app) {
  app.get(
    '/api/x402/research',
    x402Paywall(RESEARCH_PRICE, '/api/x402/research', {
      description:
        'Deep web research on any question: multi-source scan (Jina/DDG/Exa/Tavily), verified brief + cited sources. Settled in USDC on Arc.',
    }),
    async (req, res) => {
      try {
        const q = String(req.query.q || '').trim();
        if (q.length < 4) {
          return res.status(400).json({ error: 'q query param required (min 4 chars)' });
        }
        const limit = Math.min(8, Math.max(1, parseInt(req.query.limit || '5', 10)));

        // Hard internal deadline so slow upstreams can't hold the connection
        // past the route timeout — partial results beat a 504.
        const result = await Promise.race([
          researchQuestion(q, limit),
          new Promise((resolve) => setTimeout(() => resolve({ brief: '', sources: [] }), 55_000)),
        ]);

        console.log(`[x402/research] served "${q.slice(0, 60)}" → ${result?.sources?.length ?? 0} sources`);
        res.json({
          ok: true,
          query: q,
          brief: result?.brief || '',
          sources: Array.isArray(result?.sources) ? result.sources : [],
          count: result?.sources?.length ?? 0,
          note: 'Sourced brief generated by the Puls research pipeline. Settled via Circle Gateway x402 on Arc Testnet.',
        });
      } catch (e) {
        console.error('[x402/research] error:', e.message);
        res.status(500).json({ error: 'Research pipeline failed', detail: e.message });
      }
    },
  );
  console.log(`[x402/research] register: /api/x402/research (${RESEARCH_PRICE} per question)`);
}

export default { registerX402Research };
